import { VOB } from './vob-types';

export const emptyVobtree = {
  [VOB.LEVEL_COMPO]: [],
  [VOB.SIMPLE]: [],
  [VOB.SPOT]: [],
  [VOB.LIGHT]: [],
  [VOB.SOUND]: [],
  [VOB.SOUND_DAYTIME]: [],
  [VOB.LENS_FLARE]: [],
  [VOB.STAIR]: [],
  [VOB.FAR_PLANE]: [],
  [VOB.FAR_PLANE_DEFAULT]: [],
  [VOB.SCREEN_FX]: [],
  [VOB.ANIMATE]: [],
  [VOB.START_POINT]: [],

  [VOB.ZC_PFX_CONTROLLER]: [],
  [VOB.ZC_ZONE_FOG]: [],
  [VOB.ZC_ZONE_FOG_DEFAULT]: [],
  [VOB.ZC_EARTHQUAKE]: [],
  [VOB.ZC_TRIGGER_WORLD_START]: [],
  [VOB.ZC_TRIGGER_UNTOUCH]: [],
  [VOB.ZC_TRIGGER]: [],
  [VOB.ZC_CS_TRIGGER]: [],
  [VOB.ZC_TRIGGER_CHANGE_LEVEL]: [],
  [VOB.ZC_TRIGGER_SCRIPT]: [],
  [VOB.ZC_TRIGGER_LIST]: [],
  [VOB.ZC_CODE_MASTER]: [],
  [VOB.ZC_TOUCH_DAMAGE]: [],
  [VOB.ZC_MOVER]: [],
  [VOB.ZC_MOVER_CONTROLER]: [],
  [VOB.ZC_MESSAGE_FILTER]: [],
  [VOB.ZC_CS_CAMERA]: [],

  [VOB.OC_ITEM]: [],
  [VOB.OC_ZONE_MUSIC]: [],
  [VOB.OC_ZONE_MUSIC_DEFAULT]: [],

  [VOB.OC_MOB]: [],
  [VOB.OC_MOB_INTER]: [],
  [VOB.OC_MOB_WHEEL]: [],
  [VOB.OC_MOB_SWITCH]: [],
  [VOB.OC_MOB_LADDER]: [],
  [VOB.OC_MOB_BED]: [],
  [VOB.OC_MOB_FIRE]: [],
  [VOB.OC_MOB_DOOR]: [],
  [VOB.OC_MOB_CONTAINER]: [],
};
