export const VOB = {
  SIMPLE: '' as '',
  NAMED_SIMPLE: 'zCVob:' as 'zCVob:',
  LEVEL_COMPO: 'zCVobLevelCompo:' as 'zCVobLevelCompo:',
  SPOT: 'zCVobSpot:' as 'zCVobSpot:',
  LIGHT: 'zCVobLight:' as 'zCVobLight:',
  SOUND: 'zCVobSound:' as 'zCVobSound:',
  SOUND_DAYTIME: 'zCVobSoundDaytime:zCVobSound:' as 'zCVobSoundDaytime:zCVobSound:',
  LENS_FLARE: 'zCVobLensFlare:' as 'zCVobLensFlare:',
  STAIR: 'zCVobStair:' as 'zCVobStair:',
  FAR_PLANE: 'zCZoneVobFarPlane:' as 'zCZoneVobFarPlane:',
  FAR_PLANE_DEFAULT: 'zCZoneVobFarPlaneDefault:zCZoneVobFarPlane:' as 'zCZoneVobFarPlaneDefault:zCZoneVobFarPlane:',
  SCREEN_FX: 'zCVobScreenFX:' as 'zCVobScreenFX:',
  ANIMATE: 'zCVobAnimate:' as 'zCVobAnimate:',
  START_POINT: 'zCVobStartpoint:' as 'zCVobStartpoint:',

  ZC_PFX_CONTROLLER: 'zCPFXControler:' as 'zCPFXControler:',
  ZC_ZONE_FOG: 'zCZoneZFog:' as 'zCZoneZFog:',
  ZC_ZONE_FOG_DEFAULT: 'zCZoneZFogDefault:zCZoneZFog:' as 'zCZoneZFogDefault:zCZoneZFog:',
  ZC_TRIGGER: 'zCTrigger:' as 'zCTrigger:',
  ZC_CS_TRIGGER: 'oCCSTrigger:zCTrigger:' as 'oCCSTrigger:zCTrigger:',
  ZC_TRIGGER_CHANGE_LEVEL: 'oCTriggerChangeLevel:zCTrigger:' as 'oCTriggerChangeLevel:zCTrigger:',
  ZC_TRIGGER_SCRIPT: 'oCTriggerScript:zCTrigger:' as 'oCTriggerScript:zCTrigger:',
  ZC_TRIGGER_LIST: 'zCTriggerList:zCTrigger:' as 'zCTriggerList:zCTrigger:',
  ZC_CODE_MASTER: 'zCCodeMaster:' as 'zCCodeMaster:',
  ZC_TOUCH_DAMAGE: 'oCTouchDamage:zCTouchDamage:' as 'oCTouchDamage:zCTouchDamage:',
  ZC_MOVER: 'zCMover:zCTrigger:' as 'zCMover:zCTrigger:',

  OC_ITEM: 'oCItem:' as 'oCItem:',
  OC_ZONE_MUSIC: 'oCZoneMusic:' as 'oCZoneMusic:',
  OC_ZONE_MUSIC_DEFAULT: 'oCZoneMusicDefault:oCZoneMusic:' as 'oCZoneMusicDefault:oCZoneMusic:',
  OC_MOB: 'oCMOB:' as 'oCMOB:',
  OC_MOB_INTER: 'oCMobInter:oCMOB:' as 'oCMobInter:oCMOB:',
  OC_MOB_WHEEL: 'oCMobWheel:oCMobInter:oCMOB:' as 'oCMobWheel:oCMobInter:oCMOB:',
  OC_MOB_SWITCH: 'oCMobSwitch:oCMobInter:oCMOB:' as 'oCMobSwitch:oCMobInter:oCMOB:',
  OC_MOB_LADDER: 'oCMobLadder:oCMobInter:oCMOB:' as 'oCMobLadder:oCMobInter:oCMOB:',
  OC_MOB_BED: 'oCMobBed:oCMobInter:oCMOB:' as 'oCMobBed:oCMobInter:oCMOB:',
  OC_MOB_FIRE: 'oCMobFire:oCMobInter:oCMOB:' as 'oCMobFire:oCMobInter:oCMOB:',
  OC_MOB_DOOR: 'oCMobDoor:oCMobInter:oCMOB:' as 'oCMobDoor:oCMobInter:oCMOB:',
  OC_MOB_CONTAINER: 'oCMobContainer:oCMobInter:oCMOB:' as 'oCMobContainer:oCMobInter:oCMOB:',
};
